## 2.9 编程模型

以下面的代码为例，在此我们希望将两个数相乘。该示例真正想要说明的是如何安排代码结构。

In [1]:
import tensorflow as tf

with tf.Session() as session:    # 使用tf.Session()指令，创建一个对象session，该对象包含计算图
    x = tf.placeholder(tf.float32,[1],name="x")    # 利用占位符（placeholder）的概念，定义了变量x和y
    y = tf.placeholder(tf.float32,[1],name="y")
    z = tf.constant(1.0)    # 定义了一个常数（= 1.0），并命名为b：
    y = x * z    # 引入想要计算的模型了
    x_in = [100]    # 定义了计算模型
    y_output = session.run(y,{x:x_in})    # 使用session.run命令执行计算图
    print(y_output)

[100.]


用placeholder函数定义一个数据或张量需要3个参数。
* 第一个是数据类型。
* 第二个是占位符的形状，本例中为一个[一维张量](https://www.tensorflow.org/versions/r0.8/api_docs/python/framework.html#Tensor)，含有一个条目。
* 第三个是变量名，选择清晰合适的变量名对代码的调试和分析大有裨益。

不要忘记，只有执行session.run()时，程序才会开始处理已定义的图元素。

## 2.10 数据模型

TensorFlow的数据模型由**张量**表示。忽略那些复杂的数学定义，可以说（TensorFlow中的）“张量”指的是一个**多维数值阵列**。

这种数据结构由3个参数描述——**阶（rank）**、**形状（shape）**和**数据类型（type）**。

### 2.10.1 阶

每个张量的维度单位用阶来描述。它定义了张量的维数，因此，也被称为一个张量的量级或张量的n个维。
* 零阶张量是一个标量，
* 一阶张量是一个向量，
* 二阶张量是一个矩阵。

In [2]:
import tensorflow as tf

scalar = tf.constant(100)
vector = tf.constant([1,2,3,4,5])
matrix = tf.constant([[1,2,3],[4,5,6]])
cube_matrix = tf.constant([[[1],[2],[3]],[[4],[5],[6]],[[7],[8],[9]]])
print(scalar.get_shape())
print(vector.get_shape())
print(matrix.get_shape())
print(cube_matrix.get_shape())

()
(5,)
(2, 3)
(3, 3, 1)


### 2.10.2 形状

张量的形状指的是其行数和列数。

In [3]:
scalar.get_shape()

TensorShape([])

In [4]:
vector.get_shape()

TensorShape([Dimension(5)])

In [5]:
matrix.get_shape()

TensorShape([Dimension(2), Dimension(3)])

In [6]:
cube_matrix.get_shape()

TensorShape([Dimension(3), Dimension(3), Dimension(1)])

### 2.10.3 数据类型

除了阶和形状，张量还具有数据类型。表2-1是张量的数据类型汇总表。

表2-1 张量的数据类型

|数据类型| Python表示| 描 述|
|:|:|:|
|DT_FLOAT| tf.float32| 32位浮点型|
|DT_DOUBLE| tf.float64| 64位浮点型|
|DT_INT8| tf.int8| 8位有符号整型|
|DT_INT16| tf.int16| 16位有符号整型|
|DT_INT32| tf.int32| 32位有符号整型|
|DT_INT64| tf.int64| 64位有符号整型|
|DT_UINT8| tf.uint8| 8位无符号整型|
|DT_STRING| tf.string| 可变长度的字节序列。张量中的每个元素都是一个字节序列|
|DT_BOOL| tf.bool| 布尔型|
|DT_COMPLEX64| tf.complex64| 复数型，由两个32位浮点型组成，分别作为实部和虚部|
|DT_COMPLEX128| tf.complex128| 复数型，由两个64位浮点型组成，分别作为实部和虚部|
|DT_QINT8| tf.qint8| 8位有符号整型，在量化型op中使用|
|DT_QINT32| tf.qint32| 32位有符号整型，在量化型op中使用|
|DT_QUINT8| tf.quint8| 8位无符号整型，在量化型op中使用|

注意，TensorFlow中数据的传递需要通过其API与NumPy数组的交互来完成。

若要使用**常数**构建张量，需要将一个NumPy数组传入tf.constant()操作符，得到一个拥有该值的TensorFlow张量。

In [7]:
import tensorflow as tf
import numpy as np

tensor_1d = np.array([1,2,3,4,5,6,7,8,9,10])
tensor_1d = tf.constant(tensor_1d)

with tf.Session() as sess:
    print (tensor_1d.get_shape())
    print (sess.run(tensor_1d))

(10,)
[ 1  2  3  4  5  6  7  8  9 10]


若要使用**变量**构建张量，将变量定义为NumPy数组的形式，并将其传入`tf.Variable`函数。结果得到一个带有初始值的变量张量。

In [8]:
import tensorflow as tf
import numpy as np

tensor_2d = np.array([(1,2,3),(4,5,6),(7,8,9)])
tensor_2d = tf.Variable(tensor_2d)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(tensor_2d.get_shape())
    print(sess.run(tensor_2d))

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


为方便程序在Python交互环境下的使用，可以采用[InteractiveSession类](https://www.tensorflow.org/versions/r0.10/api_docs/python/client/#InteractiveSession)，并在所有`Tensor.eval()`和`Operation.run()`调用中使用该类。

In [9]:
import tensorflow as tf
import numpy as np

interactive_session = tf.InteractiveSession()    # 创建InteractiveSession

tensor = np.array([1,2,3,4,5])
tensor = tf.constant(tensor)

print(tensor.eval())

interactive_session.close()    # 关闭InteractiveSession

[1 2 3 4 5]


这个类为交互情境下（如shell或IPython Notebook）的使用提供了方便——编写代码时无需不停地传递Session对象。

TensorFlow中另一种定义张量的方式是，使用`tf.conbert_to_tensor`命令

In [10]:
import tensorflow as tf
import numpy as np

tensor_3d = np.array([[[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8]],
                      [[ 9, 10, 11],[12, 13, 14],[15, 16, 17]],
                      [[18, 19, 20],[21, 22, 23],[24, 25, 26]]])

tensor_3d = tf.convert_to_tensor(tensor_3d, dtype=tf.float64)    # 名称和类型

with tf.Session() as sess:
    print (tensor_3d.get_shape())
    print (sess.run(tensor_3d))

(3, 3, 3)
[[[ 0.  1.  2.]
  [ 3.  4.  5.]
  [ 6.  7.  8.]]

 [[ 9. 10. 11.]
  [12. 13. 14.]
  [15. 16. 17.]]

 [[18. 19. 20.]
  [21. 22. 23.]
  [24. 25. 26.]]]


### 2.10.4 变量

TensorFlow中的变量是承载和更新参数的对象。变量必须初始化；当然，你也可以保存或恢复变量，用于代码分析。

In [11]:
# 实现从1数到10
import tensorflow as tf

value = tf.Variable(0,name="value")    # 创建一个变量，并将其初始化为标量0

# assign()和add()操作符仅仅是计算图上的节点，所以在会话运行之前，它们不会执行
one = tf.constant(1)
new_value = tf.add(value,one)    # 定义加法操作
update_value=tf.assign(value,new_value)
initialize_var = tf.global_variables_initializer()    # 变量必须初始化

# 可以将计算图实例化
with tf.Session() as sess:
    sess.run(initialize_var)
    print(sess.run(value))    # 第一个0是在这里打印的
    for _ in range(10):
        sess.run(update_value)
        print(sess.run(value))    # 打印从1-10

0
1
2
3
4
5
6
7
8
9
10


张量对象是指向操作结果的一个指针，并非真的含有操作的输出值

### 2.10.5 取回

为取回操作的输出，需要调用Session对象中的`run()`函数，并传入需要取回的张量。除了可以取回单一的张量节点外，你还可以取回多个张量。

In [12]:
import tensorflow as tf

constant_A = tf.constant([100.0])
constant_B = tf.constant([300.0])
constant_C = tf.constant([3.0])

sum_ = tf.add(constant_A,constant_B)
mul_ = tf.multiply(constant_A,constant_C)

with tf.Session() as sess:
    result = sess.run([sum_,mul_])    # 一次取回两个值
    print(result)

[array([400.], dtype=float32), array([300.], dtype=float32)]


产生张量输出值需要的所有op都被运行了一遍（而不仅仅是每个张量运行一遍）。

### 2.10.6 注入

注入机制将张量插入图节点，它用一个张量值暂时替代操作的输出。注入机制只用于在调用run函数时，通过feed_dict传递参数。最常见的用法是使用`tf.placeholder()`创建feed操作，并继承其他特定操作作为注入操作。

In [13]:
import tensorflow as tf
import numpy as np

a = 3
b = 2
x = tf.placeholder(tf.float32,shape=(a,b))    # 类型, 形状
y = tf.add(x,x)

data = np.random.rand(a,b)
sess = tf.Session()
print (sess.run(y,feed_dict={x:data}))

[[0.5822009  0.30065745]
 [1.5465575  0.89457905]
 [0.29138425 0.6645689 ]]


## 2.12 实现一个单输入神经元

<img style="float: right;" src="whatever.jpg" width="50%" height="50%">
<img style="float: right;" src="https://timgsa.baidu.com/7367767334589.png" width="50%" height="50%">
<img style="float: right;" src="whatever.jpg" style="width:100px;height:100px;float:left">
![2.jpg](attachment:2.jpg)


将要实现的模型模拟了一个单输入神经元，该模型的形式可参考图
<img style="float: right;" src="./imgs/2.jpg" style="width:20%;height:20%;float:left">

In [14]:
input_value = tf.constant(0.5,name="input_value") 

In [15]:
import tensorflow as tf

input_value = tf.constant(0.5,name="input_value") # 定义input_value，赋值为浮点数0.5
# 权重是传递给单神经元的输入，在训练阶段会改变，需要用TensorFlow的变量型来定义
weight = tf.Variable(1.0,name="weight")
# 期望值指的是完成网络的学习后，我们期望得到的输出值。定义为一个TensorFlow常量
expected_output = tf.constant(0.0,name="expected_output") 

# 我们想要计算的模型或输出为下面的乘积，即weight × input。
model = tf.multiply(input_value,weight,"model")

# 最基本的部分——我们需要告诉神经元应该如何学习。
# 第一个关键是要定义一个度量标准，即得到的输出与期望输出差距有多少。
# 这个度量标准就是所谓的损失函数。
loss_function = tf.pow(expected_output - model,2,name="loss_function")
# 我们必须想办法在神经元的训练阶段优化损失函数或最小化它的值。
# TensorFlow中有好几种优化函数。本例采用梯度下降法
optimizer = tf.train.GradientDescentOptimizer(0.025).minimize(loss_function)

# 使用TensorBoard。汇总的定义包括一个简单的设置步骤，其中定义了我们希望显示的参数。
# tf.summary.scarlar变量输出一个summary记录，以缓冲对应标量的值
for value in [input_value,weight,expected_output,model,loss_function]:
    tf.summary.scalar(value.op.name,value)    # (汇总的标签, 一个实数张量作为汇总的值)
# 将计算图中收集到的所有汇总合并
summaries = tf.summary.merge_all()

# 运行计算图，创建Session会话
sess = tf.Session()

# 创建SummaryWriter，将filelog_simple_stats事件写入对应的汇总记录
summary_writer = tf.summary.FileWriter('log_simple_stats',sess.graph)

sess.run(tf.global_variables_initializer())    # 运行该模型

# 我们进行了100次模拟，每次模拟都会监控summary_writer中定义的参数
for i in range(100):
    summary_writer.add_summary(sess.run(summaries),i)
    sess.run(optimizer)

SummaryWriter类提供了一种机制，用于在每条路径中创建事件记录文件，并向其中添加汇总和事件。该类对文件内容的更新是非同步的。这就使训练程序得以调用方法，在训练过程中直接向日志文件添加数据，而不需要因此放慢训练过程。

In [16]:
# 运行TensorBoard十分简单
# !tensorboard --logdir=log_simple_stats